### ISSUE TITLE
Lilypads float above water (at least when imported on Blender)

### ISSUE THREAD

**Issue by spacebanana420** [erich666/Mineways#104]
After importing a swamp area on Blender, I noticed that the lilypads were floating above water.
Lilypads are placed on the same height level as the water area they are on, but this water's size is slightly below the size of a block, making it slightly lower than blocks on the same height level, but lilypads don't follow this decrease in height so they float above the water they should be on.

![Screenshot_20221231_003730](https://user-images.githubusercontent.com/98528301/210119859-0199f0c6-99b6-4f6c-b6ba-36e3d329cfc7.png)
The lilypads are above water, more less at the same height level as the nearby blocks. Notice the reflections and the height of the farthest lilypad (the lack of texture transparency was my doing). 

Tested with Blender version 3.4.0 on Linux

**Comment by erich666** [comment]
Thanks for writing. For good or ill, this is how lily pads are in Minecraft - they are placed 1 texel-length above the water's surface. I expect Mojang did it this way to avoid what's called z-fighting, where the lily pad would be in exactly the same location as the top of the water. When that happens, you get random results: sometimes the water's atop the lily pad, sometimes the lily pad is seen first, per pixel.

So, I won't be fixing this problem. I agree that the lily pads should be closer to the water, but you'll have to hand adjust them in Blender (shouldn't be too hard, I hope). If you can think of a better solution, great! The ones I can think of are adding an "adjust  height" option in the export dialog, or a scripting-only option that lets you adjust the output height. I'm not thrilled with either one - the first adds complication to an already overloaded dialog, the second is pretty obscure and would have to be set by the user each time they exported a scene. Honestly, ideas welcome.

Here are some screenshots showing the lily pads in Minecraft and how they "float" above the surface.
![2023-01-06_11 36 57](https://user-images.githubusercontent.com/803995/211057849-5efabfa9-bd97-44a9-b996-759d11aa90fb.png)
![2023-01-06_11 36 41](https://user-images.githubusercontent.com/803995/211057878-c416f7d7-5582-4737-b8a1-97abdb39adaf.png)

**Comment by spacebanana420** [comment]
Thank you for this answer. Despite playing Minecraft for all these years, I forgot that lilypads also float in the game the same way, probably because the lack of shadows and reflections make it harder to notice. Since this effect is native to the game, I think it's good that it's present when exporting the maps, since it makes the export more faithful to Minecraft.
