### ISSUE TITLE
Ignore option for mod incompatibility error

### ISSUE THREAD

**Issue by vidhaanyadav** [erich666/Mineways#105]
Hello, I thought that there should be an ignore option for mod-related errors in cases of:

- Using WorldEdit to terraform a landscape
- Using some sort of a visual or animation-related mod.
- Using mods to enhance performance
- etc.

This would be nice if there would be an option to ignore the mod error in these cases, maybe you could even add a second confirmation/warning popup if a user clicks it just in case. I personally have used WorldEdit to remove a bunch of snow and change grass color once and it broke, which is why I'm making this.

**Comment by erich666** [comment]
Thanks for adding this, I appreciate it. I'm not sure what you, exactly. There are a number of "modded block detected" warnings in Mineways, so I'm not sure which ones you mean, or what you would prefer to have happen. It would be great if you could provide a small (modded) test world that shows the problem (attach, or email to erich@acm.org), and also say what you would like to have happen instead.

One thing that maybe would help you in the meantime is to use the "Show warning: false" script command before importing. See http://www.realtimerendering.com/erich/minecraft/public/mineways/scripting.html#soc

**Comment by erich666** [comment]
Ping on this one - I'd appreciate more explanation. I've added a way to suppress all errors/warnings/etc., see the first table entry here: https://www.realtimerendering.com/erich/minecraft/public/mineways/scripting.html#soc

**Comment by erich666** [comment]
I've added a fairly reasonable modded block translation feature so am closing this one: https://github.com/erich666/Mineways/releases/tag/v11.03
