### ISSUE TITLE
Glass panes do not render properly around walls.

### ISSUE THREAD

**Issue by CordylusLizard** [erich666/Mineways#106]
Glass panes and iron bars do not connect to the walls, like it should be intended in Minecraft. It ruins many builds. 
Here is an example comparison how looks model from Mineways and how it should look like in Minecraft.
![image](https://user-images.githubusercontent.com/8342843/216846077-39bd60ef-4ea8-488a-9f09-3e1ef637d378.png)
![image](https://user-images.githubusercontent.com/8342843/216846092-5bfc4a6e-0e9e-4d57-abd5-673961cd5df2.png)

**Comment by erich666** [comment]
Yes, thanks, this is an area I should work more on. There are lots of rules to untangle here: when is there a post, when is there a low or tall connecting wall piece. I've started to test, and "it's complicated."
![2023-02-16_10 49 53](https://user-images.githubusercontent.com/803995/219417440-05ebcb24-26de-4448-aa5d-c39e0b7423fc.png)

**Comment by erich666** [comment]
Whew, it's a deep rabbit hole. I need to do a lot more testing and adding code, but I also found today a bunch of irregularities with other blocks and how they attach. Anyway, hoping to have in a fix tomorrow, as a beta. Fingers crossed.

**Comment by erich666** [comment]
OK, fixed, I think. Probably some block connections I missed... But, try it out at: https://www.realtimerendering.com/erich/minecraft/public/mineways/downloads/Mineways_V1010_BETA1.zip and let me know, please. if you see anything wifty.

The testing grounds have grown:
![wall_testing](https://user-images.githubusercontent.com/803995/219802114-e5e5f84f-f6f8-475c-be33-52b3b4fd5c94.jpg)

**Comment by erich666** [comment]
Fixed in Mineways 10.10, https://github.com/erich666/Mineways/releases/tag/v10.10
