### ISSUE TITLE
Some of the partial blocks become faces instead of volume

### ISSUE THREAD

**Issue by gfdsggafg** [erich666/Mineways#110]
I was trying to export obj from my Minecraft buildings to make 3d-printing, and found that some of the partial blocks became faces instead of volume, thus they are not able to be printed. The blocks include stairs and walls, and this problem happens regardless of using obj or stl, or using exporting mode for rendering or 3d printing.
Hoping my poor English could be understood :-)

**Comment by erich666** [comment]
Try checking the box "Export lesser, detailed blocks" in the right-hand part of the export dialog, see https://www.realtimerendering.com/erich/minecraft/public/mineways/mineways.html#lesser

![image](https://github.com/erich666/Mineways/assets/803995/b640b7af-ec18-4d94-8fcd-a87ce21ccdca)

My apologies for not noticing your note earlier. Github was not sending me notifications properly.
