### ISSUE TITLE
Force selection into square

### ISSUE THREAD

**Issue by TheChocolateOre** [erich666/Mineways#112]
When creating a selection, allow optional constraint to square. This functionality is also available in other programs, usually by holding down Shift or Ctrl.

**Comment by erich666** [comment]
My apologies for not noticing your note earlier. Github was not sending me notifications properly.

Thanks for the suggestion. I just added it with a bit of code, it works OK. The part that's a bit strange is when you try to resize and grab an edge with Shift held down, it only allows increasing the size. But, should do the trick. Checked in and it should be in 11.02 when it comes out.

**Comment by erich666** [comment]
If you want to try a beta with this fix, it is here (and will be until the new version is released): https://www.realtimerendering.com/erich/minecraft/public/mineways/downloads/Mineways_11.02beta_no_mirroring.zip
