### ISSUE TITLE
Selection translation

### ISSUE THREAD

**Issue by TheChocolateOre** [erich666/Mineways#116]
Allow for a given selection to be translated as a **whole**, without the area size changing (atm you can only translate 1 side at a time, while the others remain fixed, effectively changing the area size).

P.S. Or maybe is present but I don't know the hotkey?
P.S.2. I'm sorry, I can't stop 'em coming..

**Comment by erich666** [comment]
I think I'm going to pass on this one - seems a little bit too much like hotkey madness. I'm kind of doubting anyone's wanting exactly square exports as it is, but that Shift operator was easy enough to add. Sliding the selection box sounds even more unlikely.

That said, if more users are into it, great - chime in, y'all. I'll post on Discord.

**Comment by TheChocolateOre** [comment]
Fair enough, just a heads up that is the final piece to the framing/centering puzzle.

1. Square it. (done)
2. Display dimensions (done).
3. A little bit to the left.. and you got the perfect frame, with the whole village in the center.

I'm happy with 1. and 2. The 3's just the cherry.
