### ISSUE TITLE
Display selection dimensions

### ISSUE THREAD

**Issue by TheChocolateOre** [erich666/Mineways#117]
Atm we only get cursor block info.

**Comment by TheChocolateOre** [comment]
I just noticed that you are away of the shortcoming. I'll leave it here, to catch future users of the feature, that might feel like something is missing.

**Comment by erich666** [comment]
OK, added to 11.03, which should be out sometime soon. Beta at https://www.realtimerendering.com/erich/minecraft/public/mineways/downloads/mineways1103_beta2.zip - try it out.

**Comment by TheChocolateOre** [comment]
Maybe I'm doing something wrong, but my lower left is like that:
![mineways](https://github.com/erich666/Mineways/assets/50585073/9fa3f327-2b92-455b-aa6d-0be65ab6318a)

It's cropped at the right by the vertical line, which I cannot move. Also, when pasisng the cursor over the terrain there are some 1 frame flashes of text that override past the vertical line, but disappear immediately.
Actually, this is how Mineways been even before this addition.

**Comment by erich666** [comment]
Right, it will always be cropped by the right edge, if you keep your window small. I'm really stuffing too much into the informational window (it used to have just the location, then I added the block type, then the biome, then the file location, and someone asked me to add to the selection box ;) ). Make the window larger and you'll see everything.

I sometimes see flashing, too, it's some Windows thing with updates to the app. There's likely some better way I should be sending update messages to Windows (e.g., notice how the word "Depth" also flashes). [Searching the internet](https://www.google.com/search?q=windows+application+UI+flashing+MFC), this is a common Windows app problem. The solutions I clicked through fall into three categories: 1) do "this one simple trick", which often get responses of "that didn't work to fix the problem", 2) do double-buffering, which is an elaborate solution I'm not going to tackle, 3) some driver or other irrelevant fix.

In the #1 category, I saw a few references to WM_ERASEBKGND and how turning it off, essentially, would help, e.g., [this ancient post](https://www.catch22.net/tuts/win32/flicker-free-drawing/) from 2001. I even tried it. It did nothing (I was at least hoping for a comical error on the screen - no luck).

Closing this one, as it's in the "working as expected, in weaksauce Microsoft fashion" category.

**Comment by erich666** [comment]
Example:

![image](https://github.com/erich666/Mineways/assets/803995/1d864e6d-35e9-443d-8506-ba57b2db7b76)

**Comment by TheChocolateOre** [comment]
Interesting..
I'm on maximazed though, still no lack, the vertical line is at same spot it was in small window.
Looking at your UI, the vertical line is happily at a good spot.

**Comment by erich666** [comment]
Ha, funny, that's Microsoft weirdness. Wherever the dividing line is when you maximize your window, that's where the line stays when the window is maximized. So, to "move" that line you need to manually widen Mineways, _then_ maximize it. Goofy.

**Comment by TheChocolateOre** [comment]
Works!
