### ISSUE TITLE
Elavation shading crash

### ISSUE THREAD

**Issue by TheChocolateOre** [erich666/Mineways#118]
With elavation shading turned **on**, setting the height to -63 crashes Mineways.
The crash happens even if we navigate to -63 with ES **off** and then turn ES **on**.
-64 is safe.

This is just an inconvenience, as -63 doesn't contain that much information anyways, the problem is that it gets in the way when _scanning_ with ES **on** and reaching that height.

**Comment by erich666** [comment]
OK, fixed - I now protect against division by 0, which can end the universe as we know it. :)

The fix will be in 11.04.

**Comment by TheChocolateOre** [comment]
Damn, I was suspecting division by zero, and was about to jump in. You fast.

**Comment by erich666** [comment]
Should be fixed in v11.04 - let me know if the fix fails for you.

**Comment by TheChocolateOre** [comment]
Works as expected.
