### ISSUE TITLE
Better application icon

### ISSUE THREAD

**Issue by JMY1000** [erich666/Mineways#12]
Though the current icon works fine as is, it's rather low res and plain. I've been testing a few potential icons that I feel showcase the abilities of Mineways and fit the style of the Minecraft icons. They're far from what I would consider final, but I'll upload them here.

**Comment by JMY1000** [comment]
http://i.imgur.com/hUIRK9k.png

**Comment by JMY1000** [comment]
![](http://i.imgur.com/DEBOrHU.jpg)

**Comment by erich666** [comment]
Thanks! (And thanks for all the other reports, I'm hoping to work on them at some point.)

I was trying some other icons, and the tricky part is making sure it's resolution independent, to some extent. Sometime's the icon's tiny, sometimes large, and I want it to look reasonable under all zoom levels (which it currently doesn't). I'm also so used to the icon (as are others, I assume) that changing it might throw off the user a bit. Still, I should give this idea a poke and see if there's something I like.

**Comment by JMY1000** [comment]
![](http://i.imgur.com/6SATKs3.png)

Ignore that plane for now, it's a placeholder to block the lower part of the redstone torch that sticks out.

**Comment by erich666** [comment]
This newest one is not bad (though the shadows seem funky, and that torch in the rear is super-dark). I wish Mineways was for electronic circuitry in Minecraft, and for that matter I wish Mineways properly tracked whether redstone wires were on or off. So, I'm a little hesitant on this one. I definitely want to pick something that isn't a Minecraft tile. Hmmm, maybe use Sphax or similar... Anyway, keep the ideas coming!

**Comment by erich666** [comment]
I've put in a new icon, a picture of the first 3D print I made. It's still the teapot, giving continuity, and the teapot is [a famous computer graphics icon](https://www.youtube.com/watch?v=DxMfblPzFNc) (hey, that's my voice) so I have a fondness for it.
