### ISSUE TITLE
Crash on exporting OBJ with detailed blocks

### ISSUE THREAD

**Issue by jae1911** [erich666/Mineways#121]
Hey there, I'm having a crash when trying to export parts of a map for rendering.

How to reproduce:
1. Load map and select area
2. File -> "Export for rendering"
3. Save as type "Wavefront OBJ, relative"
4. On the export window, uncheck "Export lesser, detailed blocks"
5. Hit "ok"
6. Export will begin and Mineways will crash when nearing the end

Tried:
1. Use the "for_old_machines" version
2. Check Help -> "Give more export memory!"
3. Exporting parts of another world, issue remains

OS used: Windows 11
Mineways version: 11.03

**Comment by erich666** [comment]
Ah, thanks for reporting this problem. Right, if you turn off lesser blocks, Mineways compensates by making a bunch of new textures to represent these missing blocks, e.g., gluing plants onto grass block tops. If you want to use this mode, you must select the "three textures" export option (or, any other mode than "individual textures"):

![image](https://github.com/erich666/Mineways/assets/803995/903e9ff8-8e27-42c1-b93a-03b39043f825)

I'll fix this in the next release, i.e., it will force this mode if not already selected.

**Comment by erich666** [comment]
Should be fixed in v11.04 - let me know if the fix fails for you.

**Comment by jae1911** [comment]
Can confirm, it does work now!  
Thanks a lot!
