### ISSUE TITLE
Conditionally export individual blocks

### ISSUE THREAD

**Issue by TheChocolateOre** [erich666/Mineways#122]
This leans towards the _let's casually talk about this_.

So, the thing is, exporting individual blocks while your selection contains water, you get something like:
![water_edges](https://github.com/erich666/Mineways/assets/50585073/8ce2f608-bfdf-429b-a92d-ebe4e6260255)
and that translates as is in the final render. 
Of course, it's obvious why, cause you have duplicate faces (**you asked for it**), water is transparent, 1 + 1 = you get it.

But, what if you could communicate _somehow_ (we can paint the bikeshed later) to Mineways, that Yes you want individual blocks, but for water only, look the other way. 
_Problem solved ... right?_ 

Yes, that would leave the door open to request like:
`Why stop at water? Why not specify another block?` 
`You know what, why only a single type of block, why not a collection of blocks?` 
`You know what forget all of that, I need performance, I only what individual blocks for this region, why I have to pay for everything?!` and yeah ...

Anyway, the problem is with transparent blocks. Of course, you can manually fix it, but you have to dive in and remove them (the faces) and sometimes there are a lot of them and sometimes it's glitchy, etc...

Just a small chat, I can definetly live without this one. :)

**Comment by erich666** [comment]
There's already a way, I think: use [Color Schemes](https://www.realtimerendering.com/erich/minecraft/public/mineways/mineways.html#schemes). Set up two schemes: in one, everything is visible except water (still and flowing) - you set the alphas for those to 0. Export individual blocks (and definitely set Absolute coordinates, I think). Now set up a second color scheme, one where everything is transparent except for still and flowing water. Export normally, not individual blocks. Voila, you have two exports, one model with individual blocks for everything but water, the other for water, merged. Load both files and you're done.

Or if you want to get crazy fancy, where you have just one OBJ file holding the export, you could export to the "relative" OBJ format for each, then simply put both OBJ files in a single OBJ file (still need both MTL files, short of hand-editing).

Hopefully that solves this one, so I'm closing it.
