### ISSUE TITLE
Issue when using "export lesser, detailed blocks" option

### ISSUE THREAD

**Issue by tynish** [erich666/Mineways#126]
My model very detailed, so I want the option on, but I don't want the interior included in the file, since it's fully enclosed.  When I have the option off, the interior of the build is filled in like I want, but when I turn the option on, the actual interior is kept, which I don't want, and the polygon count is enormous.  I didn't change any other options.

**Comment by erich666** [comment]
Yes, it's a problem with this combination, detailed and "Fill air bubbles." It's easy enough for the program to figure out something's an interior when everything is output as full blocks. But, partial blocks are tougher and the program's sometimes not able to do so. One headache is that sometimes the roof is made of stair blocks, which are not full blocks. Really, the "fill air bubbles" is meant more for 3D printing, where full blocks (not detailed) is the norm.

One idea would be to make a copy of your world and then fill in the entrances, windows, etc. of your interior space with full blocks. There's some documentation on the various options [here](https://www.realtimerendering.com/erich/minecraft/public/mineways/mineways.html#opt_fill), just in case you hadn't seen it.

I'm closing this one as I'm sure I'll never fix it. Like I say, the filling feature is more for 3D printing, and this is the first time in the 13 years that Mineways has been out that I've heard of anyone wanting to use it for rendering.
