### ISSUE TITLE
How does mineways applies SketchFab 3D viewer settings?

### ISSUE THREAD

**Issue by AntonIXO** [erich666/Mineways#128]
Hello. I am want to manually upload exported models to SketchFab. 
But it automatically applies trilinear filter to every texture makes it look blurry.
I found that models, uploaded using Mineways built in uploader uses nearest filter and other settings:
![image](https://github.com/erich666/Mineways/assets/25568560/f3d52f84-c2b4-48c3-80be-e60a2c9977d0)
How do you set viewer settings automatically using API?
Thanks!

**Comment by erich666** [comment]
> How do you set viewer settings automatically using API?

I'm not sure what API you mean. Mineways? There is none. Sketchfab? They have an API?

I actually don't know how they make this happen in Sketchfab (Sketchfab kindly provided the code). I just tried looking through the bits of code that they added - I'm not seeing anything obvious. Looking at a model, I don't see any place where they turn on nearest neighbor. I'll point your question out to the Sketchfab group and hope they let me or us know.

**Comment by AntonIXO** [comment]
> > How do you set viewer settings automatically using API?
> 
> I'm not sure what API you mean. Mineways? There is none. Sketchfab? They have an API?
> 
> I actually don't know how they make this happen in Sketchfab (Sketchfab kindly provided the code). I just tried looking through the bits of code that they added - I'm not seeing anything obvious. Looking at a model, I don't see any place where they turn on nearest neighbor. I'll point your question out to the Sketchfab group and hope they let me or us know.

After a few hours of research, I found this, undocumented, upload parameter: https://github.com/erich666/Mineways/blob/e6cb41c1f652c11f7236b44027509b8bbad436b3/Win/SketchfabUploader.h#L81 
Now sketchfab automatically applies needed settings -> [model](https://sketchfab.com/3d-models/demomineways-9bd85c766afb4d42b7ea425cd21ab97c) 
And adds header 
![image](https://github.com/erich666/Mineways/assets/25568560/0be79dc1-e000-4983-a1ba-3b984fc07e5d)

**Comment by erich666** [comment]
Ah, I was wondering if they keyed off of "Mineways" as a thing. I'm glad you figured it out.
