### ISSUE TITLE
Why is mineways.exe missing from all releases?

### ISSUE THREAD

**Issue by Defekters** [erich666/Mineways#130]
I needed an older version of Mineways, so I started looking for it on Github. After looking through several versions, I didn't see any that had a Mineways.exe file. Yet the ReadMe file itself asks to use this missing file.

**Comment by erich666** [comment]
The old EXE's are not in Github. Old EXE's are linked from [here](https://www.realtimerendering.com/erich/minecraft/public/mineways/mineways.html#versions).

> Yet the ReadMe file itself asks to use this missing file.

What file? I should correct that. The README.md for this site itself says "You usually want the latest version. If you have problems with it, you might try [an older version](https://www.realtimerendering.com/erich/minecraft/public/mineways/mineways.html#versions)." and links to the page I linked to above.

For old _code_ for Mineways, see [the Github releases](https://github.com/erich666/Mineways/releases). No EXE's, like I say.

I appreciate your note, as it made me read over the Github README.md and clarify some things, like the difference between downloading the EXEs and downloading the code.
