### ISSUE TITLE
[OBJ export] Torch top texture has incorrect orientation

### ISSUE THREAD

**Issue by kazarmy** [erich666/Mineways#131]
The torch top texture should be rotated 90 degrees anti-clockwise.

In Minecraft 1.21.1 (click image to enlarge):

![2024-08-19_20 17 12 (with circle)](https://github.com/user-attachments/assets/71b2fdee-3cd1-4409-a986-6c576f18392d)

In Blender 3.6 after using Mineways 12.02 (interpolation for dirt and torch textures have been set to 'closest'):

![Blender_top_torch](https://github.com/user-attachments/assets/79bb87a3-b3ed-4876-aa5b-3dd21a031bca)

This can be fixed with Blender scripting but perhaps it would be better if it is fixed in Mineways.

**Comment by erich666** [comment]
Thanks, I'll fix it eventually. Feel free to point out any other inconsistencies you find. Like I said in another Issue, I should go through all 1000+ blocks and check for these small inconsistencies, but I have plenty else to do in my life right now.

**Comment by erich666** [comment]
Fixed by https://github.com/erich666/Mineways/pull/132
