### ISSUE TITLE
1.21 not supported?

### ISSUE THREAD

**Issue by chriss59** [erich666/Mineways#134]
I downloaded Mineways version 12.02 for Windows from the Mineways website and when I export a 1.21 schematic I get these messages and the schematic file has the wrong blocks. In the GitHub releases and website it says that Minecraft 1.21 is supported?
![image](https://github.com/user-attachments/assets/678741b8-5cc4-405a-9f14-3fac6334f31d)

**Comment by erich666** [comment]
Right, the new schematic file format that some people came up with is not supported. Mineways does support 1.21. See https://github.com/erich666/Mineways/issues/40 for how to work around the problem (short version: load your schematic into a world - Mineways understands Java - Classic - worlds).
