### ISSUE TITLE
Flower pot contents are inaccurate

### ISSUE THREAD

**Issue by JMY1000** [erich666/Mineways#14]
![](http://i.imgur.com/p0G4vyV.jpg)
![](http://i.imgur.com/WyHEsFc.png)

**Comment by erich666** [comment]
See http://www.realtimerendering.com/erich/minecraft/public/mineways/mineways.html#blocks

Acacia and dark oak not identifiable by Mineways currently. Pots made in 1.7 will not have any contents, as they rely on tile entities for the contents, not supported by Mineways.

I really should bite the bullet and figure out tile entities, e.g. http://bedrockminer.jimdo.com/modding-tutorials/advanced-modding/tile-entities/

**Comment by JMY1000** [comment]
Might be useful to update the documentation page to make it 1.7 and later, as well as remove the contents removed entirely on any levels made after 1.6.4.

**Comment by erich666** [comment]
Updated the docs (visible in the next release). I believe flower pots made in 1.7 and later will always be shown as empty. By the way, how did you generate those pictures? That is, is the test world you have there available for download, or can you send it to me? Looks handy for testing. I have a similar test world (it's built in to every version of Mineways, "[Block Test World]"), but it's a bit sparse.

**Comment by JMY1000** [comment]
[Debug mode.](http://minecraft.gamepedia.com/Debug_mode) Everything was generated in 1.10, but debug mode is a little weird, and it might be that blocks like that wouldn't ever actually be created.

**Comment by erich666** [comment]
Wow, and thanks - a fascinating place is Debug world, and with two little commented-out assert() statements Mineways can export it. I just need to add redstone wire and tripwire hook export and I'll have the new version done...

The good news is that today I discovered that Minecraft has (finally) added a way to tell what version Minecraft world the file is: the Version ID is greater than zero when the world is 1.9 or newer. So I've turned everything into empty flower pots if the version is 1.9 or newer. This will be in version 5.01.

**Comment by JMY1000** [comment]
Awesome, can't wait!

**Comment by erich666** [comment]
Partial fix is in V5.01, i.e., all pots are now empty.

**Comment by erich666** [comment]
I've added code that now reads Block Entities (boy was that a pain), stores this additional data away, and uses it when reading the world for export. This addition also turned up a bug fix, that acacia and dark oak saplings were not exporting properly. Long and short: flower pots are now filled. This fix will be in version 5.04.

**Comment by erich666** [comment]
Indeed fixed in [Version 5.04](https://github.com/erich666/Mineways/releases/tag/5.04) and ready for download.
