### ISSUE TITLE
Torch flames as separate objects

### ISSUE THREAD

**Issue by CrankerMan** [erich666/Mineways#15]
Just as the title says

**Comment by erich666** [comment]
Thanks for adding it to the list.

Torch flames are animated - any opinion on what their neutral position should be?

Note to self: I should probably figure out if there's some way to stop animation in Minecraft itself - do you know of any? I spend ridiculous amounts of time staring at non-moving Minecraft objects to reverse engineer them. Doing this for animated objects makes it harder still.

**Comment by JMY1000** [comment]
Install Optifine, then go to Options -> Video Settings -> Animations... and toggle as needed (there's even all on/off buttons!)

**Comment by erich666** [comment]
Excellent, thanks! I've been meaning to check out the latest Optifine, this gives me another reason to do so.

**Comment by frogg** [comment]
I just found this issue using the search – I was researching if it‘s possible to export animated files from Mineways as well (I think `.DAE` files for example support animated 3D objects).

My interest is around exporting Redstone circuits as 3D files, but animated so you can actually see pistons moving in/out for example.

Just a general question, if this is possible and if you know any starting point for me!

Thanks a lot for this great plugin, I love it!

**Comment by erich666** [comment]
Hmmm, I don't know. I would ask @TheDuckCow, as he works on [MCPrep](https://theduckcow.com/dev/blender/mcprep/) and so likely would know more.

**Comment by erich666** [comment]
If you export to USDA format in Mineways 8.00, you should get an emissive texture map for some of the emitters. It's something I hacked in so that torches and other emitters look reasonable in USD. Even if you don't use USD, you can always export to the format and simply get the textures produced by Mineways to use as you wish.
