### ISSUE TITLE
It'd be nice to get ports to Linux/Mac

### ISSUE THREAD

**Issue by waddlesplash** [erich666/Mineways#2]
This would involve rewriting all the GUI code into some cross-platform toolkit (I personally recommend Qt, as it's the easiest to use and the most powerful.)

This tool is useful enough to me that I'd be willing to help out with this.

**Comment by erich666** [comment]
The more I think about the effort of porting to Qt, the more I realize how uninterested I am in spending weeks/months to do so. If someone else wants to do it for me, great!

**Comment by ParkerMc** [comment]
I am a linux user would you like me to port it to linux? I just found this project and it is amazing.

**Comment by erich666** [comment]
@ParkerMc Feel free to take a stab at it. Note that Mineways is built atop [Minutor](http://seancode.com/minutor/), which is platform-independent. Minutor has gone considerably further along the path of platform-independence by moving to Qt, so if I were to undertake this task (which I'm not), as I mention above I'd probably rebase the Mineways code atop their new user interface code, or at least look to see how they did it.

**Comment by ParkerMc** [comment]
To make it a little easier could you tell me how you made it in the 
first place so that I can kinda just do that and use your code as a 
reference? I can email you or what ever is best.

**Comment by erich666** [comment]
Sure, here's a quick way to compare where Minutor's and my version diverged.

Minutor's version 1.5 is approximately the version I started from back in 2011 as the basis for Mineways: https://github.com/mrkite/minutor/releases/tag/1.5

The source for my first version is here: http://www.realtimerendering.com/erich/minecraft/public/mineways/mineways.html#versions, specifically [this link](http://realtimerendering.com/erich/minecraft/public/mineways/MinewaysSourceV100.rar).

Do a "diff" and you'll see where things diverge. In the MinutorMap and MinewaysMap directories is the platform-independent code, no Windows UI etc. there. I change MinutorMap to MinewaysMap, and add ObjFileManip, the now-giant, sprawling file that does all the file conversion, along with files to support reading and writing PNG image files.

In the Windows subdirectories, the projects differ a little. I add an ExportPrint dialog, a single giant "here's all the options" dialog just to make it obvious what all the options are.

And that's about it. Minutor's had [new releases](https://github.com/mrkite/minutor/releases), and I'm guessing 2.0.1 is where they went to Qt. Mineways has had more and more added to it, but not a lot of UI or Windows-specific stuff, mostly just new menu items. Probably the most significant piece is the stuff Sketchfab added, that attaches to the web for exporting the model.

Hope this helps. It makes me realize that converting to Minutor's platform independent Qt code is not inconceivable - I guess I'd do a diff between 2.0.1 and 1.5 and see where they went. Anyway, I need to get back to working on [our book](http://realtimerendering.com), which will keep me busy until August.

**Comment by ParkerMc** [comment]
Got it thanks a lot.

**Comment by erich666** [comment]
Probably not ever going to happen - it'd be a ton of work, and there are fine alternatives, such as [WINE and Crossover](http://www.realtimerendering.com/erich/minecraft/public/mineways/downloads.html#macPlatformHelp). Closing this one.
