### ISSUE TITLE
How to export with custom and nicer materials?

### ISSUE THREAD

**Issue by acterhd** [erich666/Mineways#22]
Hello. I have few questions. How export with custom materials, properties and textures? 
For examples, make iron reflective, ice refractive, add normal maps... 
Also, with nicer Water... 

My renderer have native support of reflections.

**Comment by erich666** [comment]
You'll have to figure these sorts of things yourself, to be honest. Mineways gives you the raw geometry and textures you need, but exports only basic simple color textures and generic material settings. It's up to you to learn Blender or whatever rendering package you're using - there are plenty of materials if you google around. You say "my renderer", but not which one, so I can't point you to anything in particular. The Mineways documentation does have some tips on making slightly better [water for Blender](http://www.realtimerendering.com/erich/minecraft/public/mineways/mineways.html#blender) at step #8, for example. It'll be up to you to find or generate normal maps, etc. There are some resource packs that support such things, e.g., see [this page](http://www.minecraftforum.net/forums/mapping-and-modding/resource-packs/2690082-resource-pack-shader-support-parallax-pom-bump).

**Comment by acterhd** [comment]
If fix transparency, properties change possible, but will some problems
with settings normal map, because water have own texcoords...

**Comment by JMY1000** [comment]
What program are you using?

**Comment by acterhd** [comment]
My own-written path tracer. 
"phantom-tracer"
Have no so much FPS, but may support dynamic scenes.

**Comment by JMY1000** [comment]
I don't think there's much I'll be able to do to help you then.
