### ISSUE TITLE
Mineways cannot load minecraft world with missing dimensions

### ISSUE THREAD

**Issue by cthbleachbit** [erich666/Mineways#24]
I received a copy of map from a server owner, and the server has dimensions stored in separate folders. When trying to load the world, mineways gives an error. I'm using wine on Linux.
![screenshot from 2016-12-18 15-20-05](https://cloud.githubusercontent.com/assets/3353318/21296622/7b4475ec-c535-11e6-95e9-5adb79df23de.png)

**Comment by erich666** [comment]
So, it's not a Pocket Edition or Education Edition or Windows 10 Beta
edition? All those non-Java-based versions of Minecraft use a different
file format that Mineways does not read.

If the world's from "classic" Minecraft, and not modded, it should read in.
If you want to send me the level.dat file, I can tell you if it's readable.

Eric

**Comment by erich666** [comment]
Any luck figuring this out, @cthbleachbit ? I recently made some important fixes to Mineways for Windows, version 5.10 - please do try it out.

**Comment by cthbleachbit** [comment]
It works now. Thanks a lot.
