### ISSUE TITLE
Please release 1.12 version on 1.12 site, or make building much easier.

### ISSUE THREAD

**Issue by dordsor21** [erich666/Mineways#29]
Not able to build because Microsoft in all their glory make VS far too convoluted, so I am unable to install 8.1 SDK in a fashion that works with my current (half-broken) installation of VS 2015. Because Microsoft.

The downloaded version from main site does not support 1.12 blocks.

**Comment by erich666** [comment]
Sorry that I can't help you with VS 2015 - works fine on my three machines.

> The downloaded version from main site does not support 1.12 blocks.

What exactly do you mean? Which blocks? Or do you mean textures? Version 5.09 does, AFAIK - please be specific. Note the 1.12 blocks in this scene generated with Mineways export: https://s26.postimg.org/ki5njsba1/1.12.jpg

**Comment by dordsor21** [comment]
loaded it up with a 1.12 map, and concrete/etc was replaced with bedrock. Also using the TileMaker, 1.12 blocks are not supported. (Using version and all downloaded from main site)

**Comment by dordsor21** [comment]
![image](https://user-images.githubusercontent.com/10080017/28624524-4899de46-7211-11e7-98c3-e777fe91d56c.png)
this download

**Comment by dordsor21** [comment]
let me remake. This is messy.
