### ISSUE TITLE
TileMaker doesn't support properly 1.12 blocks

### ISSUE THREAD

**Issue by dordsor21** [erich666/Mineways#30]
Errors when using (cleaned up a bit): https://hastebin.com/uqovowuver.sql there are probably some wrong texture names in there, but most are correct from what I can find in MC textures/blocks

**Comment by erich666** [comment]
It feels like you're using an old version of TileMaker - I just downloaded and tested the latest, and it finds the new files just fine. The latest is v2.04, file dated June 9, 2017. Type
`tilemaker -v` and take a look. If it's not v2.04, get the newest. If it *is* v2.04, do:
`TileMaker.exe -d blocks -o terrainExt.png -m -v` and [send me](http://www.realtimerendering.com/erich/minecraft/public/mineways/contact.html) the output.

**Comment by erich666** [comment]
Ping @dordsor21 . Let me know if you are still finding the bug; if not, great, I'll close the issue. If so, send me a zip with your blocks and I'll try it here.

**Comment by dordsor21** [comment]
Works. It was a mix of not quite 1.12 compatible, and wrongly-named extra image sin the res pack.
