### ISSUE TITLE
Export image command line options to application. Question.

### ISSUE THREAD

**Issue by Came1ot** [erich666/Mineways#33]
I want to export rendered minecraft schematic to jpg or png file using command line options of Mineways.
I have huge schematic pack and I want to render it all automatically using script.
Is this possible?

**Comment by erich666** [comment]
Mineways does not do rendering, it just exports data. Mineways can read the schematic and export it to OBJ or VRML formats, commonly used by rendering packages such as Blender (which is free).

**Comment by Came1ot** [comment]
Can I convert *.schematic to *.OBJ using the command line?

**Comment by erich666** [comment]
You can use the [scripting interface](http://www.realtimerendering.com/erich/minecraft/public/mineways/scripting.html) to do everything from the command line: start up, read schematic, export, and close. See
