### ISSUE TITLE
[feature request] Language localisation

### ISSUE THREAD

**Issue by scollovati** [erich666/Mineways#36]
Hi,
I was wondering if you had in mind to implement localisation of the strings.
In that case I'll be very happy to contribute to the italian translation.

**Comment by erich666** [comment]
Thanks for the offer. Mineways is just a free hobby program, so I don't plan on spending my spare time localizing the code. As it is, there's going to be a lot of work [converting over to the new Minecraft format](https://github.com/erich666/Mineways/issues/35), so I'll be focused on that.
