### ISSUE TITLE
Add secondary biome textures

### ISSUE THREAD

**Issue by erich666** [erich666/Mineways#37]
Ryermeke [writes in the Minecraft forum](https://www.minecraftforum.net/forums/minecraft-java-edition/discussion/326119-mineways-3d-prints-of-minecraft-objects?page=22#c490):

So, I read through your wish list thing on the website, and there is listed biome support... but you haven't done it due to the transition blocks being difficult. That's all fine, but could you potentially add support for biome specific textures? This wouldn't need the different biome colors to be exported, just the secondary textures assigned to different biomes. In particular, a pack that I use has 32 different glass textures, with the other 16 being visible only in the Forest Hills biome. The textures, granted, are only visible using Optifine, and they are not located in the same location as the rest of the textures (instead located under mcpatcher/ctm), but I would think it would be easier to implement than full biome support.

He includes two screenshots.
-----------

My reply is: Probably not. There's relatively little interest in biomes overall, you're about the first who has asked for any improvement to the (limited) biome support Mineways has.

**Comment by erich666** [comment]
You can always make your own texture set using the TileMaker, though of course only one tile set is used at a time. But, you could also make separate exports, using one set of tiles for one area of the map, one for another. One interesting idea I might be able to easily add is to "export only biome XXX" as part of scripting, so that each biome could have its own tile set. I'll think about that.

**Comment by erich666** [comment]
Well, biomes got even crazier (3D, etc.) in 1.19, so I think I'm going to call it a day on further biome support, especially for modded resource packs with multiple biome-specific textures (amazing!).

**Comment by mguggenheim** [comment]
@erich666 I'm working on a Minecraft to Unreal Engine plugin, and I wanted to add biome support, so I was curious what you were referring to about biomes getting even crazier in 1.19. Curious what kinds of hurdles you saw that I should be prepared for.
