### ISSUE TITLE
How to iterate each building and export the model?

### ISSUE THREAD

**Issue by yobichi** [erich666/Mineways#4]
I am running a server and there are a big numbers of buildings and I want to export all of them. How can I do that after downloading your code? Which part of it should I look into and what information is necessary to export them?

**Comment by erich666** [comment]
There's currrently no programmatic way to run Mineways and feed it coordinates, if that's what you mean. If you mean "how do I use Mineways?", please see the quickstart page here: http://www.realtimerendering.com/erich/minecraft/public/mineways/downloads.html - really, it's simple, watch the tutorial, https://www.youtube.com/watch?v=xmsnE85GNV8

**Comment by yobichi** [comment]
@erich666 Thanks for reply. What I want is using the code of Mineways to get the 3D object file. It would be great help if you can tell me which part of code I should use or modify. Thanks in advance.

**Comment by erich666** [comment]
Sure, WriteObjBox in [ObjFileManip.cpp](https://github.com/erich666/Mineways/blob/master/Win/ObjFileManip.cpp) is where the OBJ file actually gets written out.
