### ISSUE TITLE
Mineways site is down.

### ISSUE THREAD

**Issue by ItsCheif** [erich666/Mineways#46]
Thought I'd bring this to your attention so we can get this fixed ASAP. One of my subscribers just told me that the Mineways site is down, upon further inspection, it is.

www.realtimerendering.com/erich/minecraft/public/mineways/
^ Doesn't work anymore.

**Comment by ItsCheif** [comment]
Thanks for all you do Erich, you're a legend ;)

**Comment by erich666** [comment]
Yes, we went down because a too-large file was uploaded to the site as a whole, which mysteriously violated Bluehost's terms of service in some indeterminate way. Good times. Anyway, it's back up. And, yes, I'm a legend in my own mind.
