### ISSUE TITLE
Ground/ceiling buttons don't export properly

### ISSUE THREAD

**Issue by roket333** [erich666/Mineways#51]
If there is buttons on the ground or ceiling, like in the screenshot below
![image](https://user-images.githubusercontent.com/5241048/71802267-7b0db400-301a-11ea-85e1-e0b61b5ca99e.png)
when exported, they always face north/south, like in the shot below
![image](https://user-images.githubusercontent.com/5241048/71802377-c4f69a00-301a-11ea-8d4f-5e886db1855b.png)
I would imagine this also happens with blocks like levers too

**Comment by erich666** [comment]
Ha, funny you should mention - I fixed this yesterday, thought I have not checked in the fix yet (I'm making many more fixes). Given your interest, please email me at erich@acm.org and I can send you a beta version to test out - you then get this fix now.

**Comment by roket333** [comment]
i like to help however i can, especially for such a useful tool
also i fixed it manually soon after submitting this
i also appreciate the offer, and depending on the reception to the project i am using this for, i'll take you up on it

**Comment by erich666** [comment]
Fixed and released in version 7.10. Thanks again for reporting this.
