### ISSUE TITLE
The top of flowing water uses the static water texture

### ISSUE THREAD

**Issue by roket333** [erich666/Mineways#52]
Fairly self explanatory
![image](https://user-images.githubusercontent.com/5241048/71845320-471ba880-3085-11ea-8e2b-f58b8e2bea73.png)
When exported, flowing water uses the static water texture on top instead of the flowing water

**Comment by erich666** [comment]
Oh, thanks - good catch. I'm not sure I'll fix this one, to be honest, as it's pretty tricky, e.g., when the water flows diagonally the texture needs to be applied diagonally. Possible, but hmmm. Anyway, I'll think about it.

**Comment by erich666** [comment]
Can't really fix this one, as the "single image" output texture won't allow it - the flowing water texture does not "repeat" but is just a single instance, so the neighboring images would interfere with it. I could fix this for the "export tiles for textures" mode, as the flowing texture could then repeat in the renderer using it, but it would only work for that sort of texturing. So, I have to pass on this fix.
