### ISSUE TITLE
Command line conversion of Schematic to OBJ/STL

### ISSUE THREAD

**Issue by acs** [erich666/Mineways#55]
Hi!

As with Schematic files you don't need to do any map selections, is it possible to just call mineway as a format converter to get a schematic file and generate a OBJ/STL file/s?

Thanks!

**Comment by erich666** [comment]
This can easily be done in Version 7.14. Make a script file, call it say "schematic_to_obj.mwscript". Read the file in Mineways using File > ImportSettings. Here's the file's contents:

> Minecraft world: C:\Users\erich\Documents\_Documents\Mineways Exports\eiffel.schematic
> Selection location: all
> Set render type: Wavefront OBJ absolute indices
> Export for Rendering: C:\Users\erich\Documents\_Documents\Mineways Exports\my_eiffel.obj

It reads in the schematic eiffel.schematic and exports it to my_eiffel.obj.

You can also run from the command line by:

> mineways.exe schematic_to_obj.mwscript

Read about other scripting commands here: http://www.realtimerendering.com/erich/minecraft/public/mineways/scripting.html#clo

**Comment by acs** [comment]
Cool, I need to find the correct way to pass params using wine in Linux, but I will follow this scripting way. Thanks!
