### ISSUE TITLE
Run from command line without Windows UI

### ISSUE THREAD

**Issue by erich666** [erich666/Mineways#56]
From Moo-Ack! Productions:

1) Running truly headless. I think this is the biggest part of the request, as currently the window still pops up and then is minimized, and takes focus away from the blender interface, which is awkward. 

2) If unable to do the above, it would be nice to stream inputs. This would solve the issue such that Mineways would only have to pop open once but then the user could continue using Blender and as they need to run other commands. To explain when this might happen:

If I want to batch imports at the Blender level; e.g. if the user selects a large export area, I might want to break it into multiple individual calls to Mineways. This would allow me to have the exports run in the background while the user continues using Blender otherwise, but most importantly would allow them to hit cancel or pause; I could not do this if I put all chunk export statements in a single script (and there is no easy way for me to gracefully kill a child process, not great design anyways). By being able to stream inputs, I save the time spent loading the world each time AND avoid having the window popup (just to be auto minimized) and stealing focus from the main blender window.

I’m toying with different world loading experiences, where you select a world and it just immediately load a central chunk. Then in the Blender interface, you would have something like placeholder blocks placed around the perimeter which you could click on to trigger exporting a slightly wider region. This lets the user only export what they want without having to wait for full exports to complete to see what it looks like. Again in this case, being able to stream additional inputs would avoid reloading the world every time, and at least avoid the step of the Mineways window popping up, being minimized, but still stealing window focus.

In this mode of “keep importing more chunks/selections as you go”, the user would explicitly decide when to end this mode, which would prompt closing the (minimized) Mineways window.

Not really phrased in user-story format but hopefully this helps! I should say that really the biggest difference would be with #1 though, avoiding the window from popping up at all. Point #2 is still manageable with the window popups, just not quite as seamless for the user. So if it’s also major re-architecture, I’d say not that worth it.

**Comment by TheDuckCow** [comment]
Thanks for posting here - let me know if you have any other questions!

**Comment by Mhowser** [comment]
Any progress on this?

**Comment by erich666** [comment]
I've thought about it a bit (really!), but given that few users would benefit from it, it's not a priority. Properly handling stairs and wall properties modified with the Debug Stick might rate higher (though that one's pretty obscure, too).

Thanks for the ping, though - that means there are two people interested, vs. just one (and I rule-of-thumb it that for every person that speaks up for a feature, there are probably 25 that don't).

**Comment by Mhowser** [comment]
Thanks for the response! I think this will benefit everyone that needs a simple and efficient workflow. And as a full time Linux user, I greatly welcome this.

**Comment by Mhowser** [comment]
Its been a while (so long I actually forgot about this), I was wondering if this is still being considered.

**Comment by erich666** [comment]
Thanks for checking in, and the answer currently is "no." It'd be a lot of work. I'd rather put the time into exporting physically-based materials to USD, which is where I've been spending my time. I dream someday that someone (else) who has good higher-level design skills for software (I tend to not have these) and boundless energy makes such a thing. I think the JSON files of Minecraft could be read and used to control most of the input and mesh output, if not all, which would mean that new blocks and modded blocks could then be supported automatically. But, that's a lot of work.

Mineways is creaking under the load of having evolved for nine years and through one major file storage change by Mojang. I'd certainly be happy to see a newer utility for exporting meshes take shape. It just likely won't be me, unless I retire sometime realsoon.

**Comment by erich666** [comment]
Classifying as "wontfix" for now but leaving it open, so others see it.

**Comment by erich666** [comment]
Closing this one, as no one seems to be strongly interested in this topic in the past two years. I can always revisit it someday, but I'm thinking I'll personally never do it - the UI and engine are quite interwoven and the gain is minimal ("awkward interaction with Blender").

I do hope the recent changes to how errors, warnings, and information messages can be suppressed goes some fair bit towards addressing some of the problems you mention. Basically, you can now suppress these when a script runs, and if you want send them instead to an error log (text file) of your choice. See the first two commands [listed in this section](https://www.realtimerendering.com/erich/minecraft/public/mineways/scripting.html#soc).
