### ISSUE TITLE
Cubic chunks world support ?

### ISSUE THREAD

**Issue by T0biasCZe** [erich666/Mineways#57]
Would it be possible to add support for cubic chunks world ? Cubic chunks is mod that remove minecraft height build limit, which is great for larger and taller building, but MW currently load it as blank world.

**Comment by erich666** [comment]
Everything's possible, but I personally don't spend time working on mod support, since there are so many of them, with so many features, and such small audiences. See https://github.com/erich666/Mineways/issues/44
