### ISSUE TITLE
Why when I tried to run t it says unknown publisher

### ISSUE THREAD

**Issue by weathon** [erich666/Mineways#58]

**Comment by erich666** [comment]
That's true, I'm not a multinational conglomerate with a registered company; I'm just a hobbyist. Like it says [here](http://www.realtimerendering.com/erich/minecraft/public/mineways/downloads.html#windowsPlatformHelp):

> If you get "Windows protected your PC" when running Mineways, click on "More info" and then "Run anyway". Run the mineways.exe executable through VirusTotal to feel safe. 

Go to that page to read more about what you can do. Basically, I'm trustworthy, and you'll have to override any "unknown publisher" notices. If you can't override the notice, then I suggest right-clicking on Mineways.exe and running as administrator. If that doesn't do it, you'll need to search the internet for ways to override any warning you get. I don't know exactly what notice you were getting, so I can't help you further.
