### ISSUE TITLE
Block read error on 1.15.2 world

### ISSUE THREAD

**Issue by wolfiee34** [erich666/Mineways#59]
It's a dedicated server world on 1.15.2 vanilla, when I open it in Mineways it doesn't fully render, and when I try to move to the unrendered area lots of block read error windows pop up. Also, jump to player is not working, as it jumps to the spawn point instead of any player (there are 4 players on the world, so I don't know if that could be a problem).

**Comment by erich666** [comment]
Have you downloaded the latest version, 7.15? I just fixed a block read error for "fringe" areas, which is part of this new version. Please give that a try. If there's still a problem, I'd appreciate it if you could send me your world - please [contact me](http://www.realtimerendering.com/erich/minecraft/public/mineways/contact.html).

Yes, jump to player works only for a single player. I should look into how to make it cycle among multiple players.

**Comment by wolfiee34** [comment]
The issue does not persist after updating, thank you.
