### ISSUE TITLE
CyclesMineways.py is outdated

### ISSUE THREAD

**Issue by JMY1000** [erich666/Mineways#6]
https://github.com/JMY1000/CyclesMineways has the latest stable release (v1.2.0) with significant changes. I'd like to see that reflected here.

**Comment by erich666** [comment]
Thanks! I'm working on an update for Minecraft 1.9, which was just released, so will include your new version in that release. You might want to check out 1.9 yourself and update your script accordingly.

**Comment by JMY1000** [comment]
Will do!

**Comment by erich666** [comment]
I put the latest version in Mineways 4.15 and pointed to this Github
repository. Please do inform me when there are further updates.

**Comment by JMY1000** [comment]
I would like to note that the comment is inaccurate, it doesn't include 1.9 blocks yet.

**Comment by JMY1000** [comment]
Again, since I've updated it again with minor changes, I think it'd be a good time to update the bundled version.

**Comment by erich666** [comment]
I'll be making a new distribution of Mineways sometime soon. In the meantime, I've put this new version of CyclesMineway.py (quietly) in the current zip downloads.
