### ISSUE TITLE
world disappears when running on ubuntu 20.04 with wine

### ISSUE THREAD

**Issue by mathlet** [erich666/Mineways#64]
Every time I try to select an area or alter the depth in a 1.15.2 world on ubuntu 20.04 the world disappears. I thought that this might be a visual bug, but when I go to export the selection, it says there are no blocks for rendering.

**Comment by erich666** [comment]
So, you can see the world before it disappears. Hmmm, I have no idea. I haven't seen this on Window. Things to try:

- Make sure you have the very latest version of Mineways
- Try both the mineways.exe and mineways32.exe versions
- Try something else than Ubuntu? I support the Windows version and am unlikely to be any help with ubuntu

Sorry I can't be of more help. One other idea is to run Mineways from the command line with: mineways -l exec.log

This will dump all sorts (really, too much) of information about what is going on with Mineways as you use it. There might be a clue in there - feel free to post it here or send it to me directly.

**Comment by TinyTophy** [comment]
I tried downloading again but got the same issue. The non 32 version doesn't even run. I assume it's built for x64 which won't work with WINE without some extra stuff. I'll just install a separate Windows partition on my laptop.

**Comment by erich666** [comment]
Give a look at this: http://www.realtimerendering.com/erich/minecraft/public/mineways/downloads.html#macPlatformHelp - Froxcey has figured out how to get Mineways to run on the latest Mac OS, after a number of attempts.

Beyond this I don't have any great advice to give you for Ubuntu. I know that people have run Mineways on Linux, but I don't have any personal experience with doing so.
