### ISSUE TITLE
error with a dll file in 32 bits

### ISSUE THREAD

**Issue by Torrex18** [erich666/Mineways#67]
hello mineways team, i just installed the program and don't want to open it, i use a win7 32 bit system and i get an error, could you help me?

 
mineways32.exe system error
the program cannot be started because api-ms-win-runtime-l1-1-0-.dll on the computer. try reinstalling the program to correct this problem.
![Sin título](https://user-images.githubusercontent.com/74017791/98282136-fc93e280-1f5a-11eb-8cd6-a37f0a405528.png)

**Comment by erich666** [comment]
See http://www.realtimerendering.com/erich/minecraft/public/mineways/downloads.html#windowsPlatformHelp

Specifically: If you get an error about MSVCR140.DLL being missing or "VCRUNTIME140_1.dll was not found" or similar, install the [Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) for your system. Select vc_redist.x64.exe if you have a 64-bit system, vc_redist.x86.exe for a 32-bit system. You may also need to reboot. (Not sure what system type you have? Press the Windows key+I, select "System", select "About" at the bottom, and look at "System type" under "Device specifications"). Sorry for this annoyance, but Microsoft does not make this easy, and the problem even has a name. Microsoft will misleadingly say "Reinstalling the program may fix this problem" - it won't. Installing the redistributable will. Still having weird problems on startup? Try looking for system corruption, advice from this post. Note: For Mineways 5.10 and earlier, you may get an error about MSVCR120.DLL being missing; install the Visual Studio 2013 (VC++ 12.0) redistributable.

I've left off all the other links - the 32-bit redistributable should fix this. If it doesn't, follow the rest of the advice and the links on [the page](http://www.realtimerendering.com/erich/minecraft/public/mineways/downloads.html#windowsPlatformHelp).
