### ISSUE TITLE
Waterlogged stairs sometimes end up oriented incorrectly

### ISSUE THREAD

**Issue by ChlorideCull** [erich666/Mineways#68]
Found this when trying to make a world to export. Those stairs are supposed to hug the wall.

Example:
![Example image](https://user-images.githubusercontent.com/4977063/102636770-5a6c3a80-4155-11eb-8df4-b0c537169a8d.png)

Here's an export and world: [repro_export.zip](https://github.com/erich666/Mineways/files/5716785/repro_export.zip) [repro_world.zip](https://github.com/erich666/Mineways/files/5716790/repro_world.zip)

**Comment by erich666** [comment]
Waterlogging is definitely a flaky feature in Mineways. Thanks for reporting this, I'll take a look at it soon. I admit to being a bit Mineways-out, after having worked like crazy to get 8.00 and 8.01 out this week.

**Comment by ChlorideCull** [comment]
Oh yeah, no rush, I'm having great fun. As a side note, a feature request: I'd love for them to not be waterlogged if there's a change block command that replaces water with air, or through a change block command. Right now I have to remove them manually in Blender afterwards.

**Comment by erich666** [comment]
Whew, fixed. Had nothing to do with waterlogging, but rather that the stairs orientation code has been using the old, pre-1.13 "what's my neighbor?" rules for deciding whether to add or subtract a sub-block from the stair block.

I finally switched over to reading in the stairs' 1.13+ properties and using them directly to determine if it's an "inner" or "outer" stairs, and left or right. This had the unforunate side effect that I had to redo 19 newer stairs, assigning each of them a separate "type" ID number internally, which hastens the day when I run out of numbers (511 is the maximum) and the code base can no longer be updated to new versions of Minecraft. We'll see how long these numbers last...

Anyway, fixed, and you can [download the beta](http://www.realtimerendering.com/erich/minecraft/public/mineways/downloads/mineways_beta.zip) with this fix.
