### ISSUE TITLE
Using names for "Change blocks" in scripts does not function currently

### ISSUE THREAD

**Issue by ChlorideCull** [erich666/Mineways#69]
Putting `Change blocks: from "wool":5 to "wool":13` from the examples on the site into a script produces the following error message:

>Error reading line 42: block type number or name not found.
>Rest of line: wool:5 to wool:13

Might have broken with a44d3f5f90a691cb115b1784c1e2b166e3fd3a88, as it seems to strip quotes, which the code looks for.

**Comment by erich666** [comment]
Oh, thanks, I'll look into this soon.

**Comment by erich666** [comment]
Whew, this simple bug led me down a merry chase. The initial fix was easy enough, but then led to a crash condition. I finally tracked it down to a "y++" that should have been a "y--" in isWorldVolumeEmpty(). Anyway, fixed, and you can find a beta in http://www.realtimerendering.com/erich/minecraft/public/mineways/downloads/mineways_beta.zip if you want to give it a try.

**Comment by erich666** [comment]
I also just realized that this code does not properly support 1.13+ block names. I've partially added that for now, and [document](http://www.realtimerendering.com/erich/minecraft/public/mineways/scripting.html#cbce) how to figure out the rest. I've updated the beta.
