### ISSUE TITLE
Minecraft 1.10 Support

### ISSUE THREAD

**Issue by JMY1000** [erich666/Mineways#7]
[Minecraft 1.10 "Frostburn Update"](http://minecraft.gamepedia.com/1.10) was recently released, and preparations need to be made for it.

This includes:

- Support for new blocks
 - Structure void
 - Magma block
 - Nether wart block
 - Red nether brick
 - Bone block
- Support for changes to previously existing blocks
 - New bounding box for rails
 - Stained clay blocks being renamed

**Comment by erich666** [comment]
This will be happening this weekend. The code's in; I'm in the process of adding one more feature, of having rails, ladders, redstone wire, etc. be separate geometric entities.

**Comment by erich666** [comment]
Done! Version 5.01 has these elements. Oooh, I didn't recall your stained clay blocks comment - fixed in V 5.02 (not released yet). My gosh, it's always something...

Anyway, marking as "fixed" since it will be, someday. If you see any other naming problems, add them here or in a new issue.
