### ISSUE TITLE
Limit of 4.7gb memory usage

### ISSUE THREAD

**Issue by LySoon** [erich666/Mineways#72]
i tried to give more export memory but still closes itself at 4.7gb of ram usage, i don't know why but i was able to use it around 38-40GB of rams for "Terrains"

so 
![image](https://user-images.githubusercontent.com/49767982/104772015-c1e0ce80-5783-11eb-8594-d189e4481bfa.png)
![image](https://user-images.githubusercontent.com/49767982/104772045-cc9b6380-5783-11eb-9259-22cab3361c66.png)

**Comment by erich666** [comment]
Yeah, that "give more memory" option is mostly meant for Windows 32, where there's a severe memory constraint.

I don't know what to tell you about Mineways using only 4.7 GB. I'll try a big export later today (I'm creating a little movie right now, don't want to mess with that) and see if I get the same result. There's nothing in mineways.exe (you're not using mineways32.exe, right?) that should limit memory use in this way - maybe it's an operating system thing? I honestly don't know, and won't have a fix if I see the same problem, so am open to suggestions.

**Comment by LySoon** [comment]
Ofc ofc, i use mineways with love so don't neet to hurry about it, im still using it for 2048 x 2048 terrain renders ^^ just wanted to report that issue. Take your time boss don't hurry :3 also thanks for that awesome tool again <3

**Comment by LySoon** [comment]
![image](https://user-images.githubusercontent.com/49767982/104821692-aa224c80-584e-11eb-8787-c09a97ba9040.png)
Guess its fixed by itself, idk why but now it works normally

**Comment by erich666** [comment]
Ahhh, the mysteries of computers. I'm glad it's working for you now. And _thanks very much_ for following up, many people don't.
