### ISSUE TITLE
Code not self consistent

### ISSUE THREAD

**Issue by rdebath** [erich666/Mineways#80]
https://github.com/erich666/Mineways/blob/6586a614eeea180ebb6f6bb6a98cac0fefaf8df1/Win/biomes.cpp#L369

The `& 7` on this line prevents any of the cases matching except `SWAMPLAND_BIOME`.

Probably a leftover.

**Comment by erich666** [comment]
Oh, thanks! I'll fix that in the next release, which should happen this week if all goes well.

**Comment by erich666** [comment]
Mesa biome now looks reasonable:

![image](https://user-images.githubusercontent.com/803995/114428138-d1f12a00-9b89-11eb-99c7-3807b4779a81.png)

Like I say, I hope to get a release with this fix out this week.

**Comment by erich666** [comment]
OK, 8.06 has the fix.
