### ISSUE TITLE
Empty space on flowers, grass, etc. are black

### ISSUE THREAD

**Issue by TurtleRunsSlow** [erich666/Mineways#84]
![image](https://user-images.githubusercontent.com/86179304/122663189-788b1580-d14d-11eb-8d50-a0bcdd8f2e83.png)
With the recent update (v8.08) flowers or grass and the like become black.

**Comment by erich666** [comment]
Are you importing into Blender? Then you need to set Blender to pay attention to the alpha channel. This has always been the case, v8.08 of Mineways is no different. Please [read the documentation](https://www.realtimerendering.com/erich/minecraft/public/mineways/mineways.html#blender) for how to properly import into Blender - using MCprep is the easiest way. 

If you're using some other program, find the instructions for it [here](https://www.realtimerendering.com/erich/minecraft/public/mineways/index.html) - scroll down and click on the name & logo of the package you're using.

Here's a shot of 8.08 data after using MCprep:
![image](https://user-images.githubusercontent.com/803995/122676548-9176e380-d1ac-11eb-9754-72b928449d93.png)
