### ISSUE TITLE
Mineways v900 crashes every time I try to export for render.

### ISSUE THREAD

**Issue by ShadowPlay1392** [erich666/Mineways#85]
I edited my world and I wanted to export it, But when ever I try to export it (its the same size of area it was when I exported it the first time) it crashes is there any way to make this stop?

**Comment by erich666** [comment]
I hope so! I don't know why it's crashing - it doesn't for me - so you'll have to figure it out on your end. There's lots of information on things to try here: https://www.realtimerendering.com/erich/minecraft/public/mineways/downloads.html#windowsPlatformHelp

Let me know if you figure it out, as I like to tell other users what might work for them in the future.

**Comment by ShadowPlay1392** [comment]
I'm thinking it might have to do with the new update cause when I exported it the first time it was the version for 1.16.5. Since its a new version maybe something screwed up on my end. (Nothing worked from that link)

**Comment by erich666** [comment]
If you could, please zip up your world's "save" directory and the file you exported (so I know where to try to export) and send these to me at erich@acm.org (or if very large, put somewhere free for download). I can then try them on my side and see if I can reproduce the crash.

**Comment by ShadowPlay1392** [comment]
I sent the file too you in an email. I also figured out that it cant be about the size cause I did a very small area (like a chunk) and it also didn't work.

**Comment by erich666** [comment]
I just noticed this - sorry! I did get your github notification, looked for files then, didn't see anything.

Looking in my inbox (and spam folder) now, I never received your files. Could you please put them in a zip file and send them again? Or upload to a free site, e.g., https://easyupload.io/ (no idea if that one's good). I would definitely like to understand this crash. Sorry I didn't get back to you sooner.

**Comment by ShadowPlay1392** [comment]
Its okay. Thank you for trying to help im sure your busy.
https://easyupload.io/r8skz1

**Comment by erich666** [comment]
Thanks, quick response, but I tried to download it and got the message below. Please post or email me at erich@acm.org the password for the file.

![image](https://user-images.githubusercontent.com/803995/127724832-8d437bfa-4c27-427f-9b72-9c64e3a6e238.png)

**Comment by ShadowPlay1392** [comment]
Its "MINEWAYSBUG"

**Comment by erich666** [comment]
Thanks, got it, and loaded the world and exported some different parts of it just fine. Here's a screenshot for one export:
![screen2](https://user-images.githubusercontent.com/803995/127725305-d07b2ed4-b616-4bec-afab-40ffc4526e19.jpg)

So this is one of those frustrating situations in which it crashes for you and not me. I don't think there's a lot I can do if I can't reproduce the crash. Some things to try: try using Mineways on a different machine, like a friend's. If it works there, at least we know it's something to do with your machine. Try making a directory c:\temp (or whatever) and try exporting to there. If that works, there's some path problem, which is a good hint (and gives you a way to keep working). Make sure your antivirus software allows Mineways to export.

Other than those, I can't think of much else. Maybe [this page](https://www.realtimerendering.com/erich/minecraft/public/mineways/downloads.html#windowsPlatformHelp) will give you some other ideas to try. Sorry I can't help more at this point - any clues you find are appreciated.

**Comment by ShadowPlay1392** [comment]
Ok thanks for the help i'll try to figure it out.

**Comment by erich666** [comment]
Give Mineways 9.01 a try, which just came out. I fixed an important, though obscure, data read error that may have caused you problems.

Or, if you figured it out in the meantime, please let me know what it was. I can then either improve the program itself, or at least improve the documentation.

**Comment by ShadowPlay1392** [comment]
All right, I'll try it out.

**Comment by ShadowPlay1392** [comment]
It would appear that it works now thanks for telling me that you updated it.

**Comment by erich666** [comment]
Oh, good - thanks for letting me know!

**Comment by ShadowPlay1392** [comment]
You're welcome.
