### ISSUE TITLE
When I export a world theres a message that says "PNG error: failed to open file for writing"

### ISSUE THREAD

**Issue by Tolmo** [erich666/Mineways#87]
![97298079-e4063700-188d-11eb-9ef4-23f51cf62799](https://user-images.githubusercontent.com/87884420/126853841-1d6befc5-9d20-4dbf-83a4-30e229bf1e34.png)
The thing is that when i export the model to blender it doesnt have textures (its all purple) and it is because of this error.

**Comment by Tolmo** [comment]
This error is a pain on the neck

**Comment by Tolmo** [comment]
wait a second...

**Comment by Tolmo** [comment]
I think i have just fixed it xD
I just needed to export the file in another place

**Comment by erich666** [comment]
Ah, thanks for explaining it a bit. I think I've heard of this bug before, but don't fully understand the solution, "export to another place." Could you describe what worked and what didn't work? Was it a file path with non-English characters causing problems? (I've tried to make that code work, so would like to know if that was it.) Please do let me know.

**Comment by erich666** [comment]
Ping on this one, Tolmo. Could you please explain what path didn't work, and what path worked?

**Comment by erich666** [comment]
Another ping on this one - Tolmo, can you explain what didn't work for you when you first tried exporting?

**Comment by erich666** [comment]
Closing, due to no response. :( I can't fix or warn the user if I don't know the error.
