### ISSUE TITLE
"Mineways-Mac-9.00" is damaged and can't be opened. You should move it to the trash.

### ISSUE THREAD

**Issue by SomeoneIDKK** [erich666/Mineways#89]
When i downloaded Mineways for wineskin this appeared for me. i don't know what to do and i really need to use Mineways.

**Comment by erich666** [comment]
Huh, strange! If I move the downloaded zip on my PC that I got from Hypersun onto a memory stick and put it on the Mac, it unzips fine and works. But if I download what I assume is the same zip (I just uploaded it again to be sure) from mineways.com, it indeed does not unzip properly! And, weirder still, if I download directly from Hypersun's location to the Mac, the zip does not work. I've taken the Mac link down for now, until we figure out the weirdness here.

**Comment by SomeoneIDKK** [comment]
Thanks for responding. there's no problem and i don't mind if you delay anything.

**Comment by erich666** [comment]
I tried a few things, e.g., https://mjtsai.com/blog/2020/12/14/damaged-apps-that-cant-be-opened/ - download it using Safari (I don't know what the "safe" thing is about). There's also the very involved https://musicdiver.com/2019/11/is-damaged-and-cant-be-opened/ which is too scary for me, but you might find it of use. I suspect it has to do with some swell feature such as quarantining that Apple is doing for you, since I'm not an approved company or whatever. Let me know if you figure anything out! The Mineways download (now hidden) is at https://erich.realtimerendering.com/minecraft/public/mineways/Mineways-Mac-9.00.zip

**Comment by SomeoneIDKK** [comment]
hey, sorry for the late response. so i tried the safari solution, same message. I then noticed i had safe mode on, so i downloaded it again, same message. then i tried the gatekeeper mode ff on chrome, downloaded it, same message. i then finally tried to download from safari with safe mode off with gatekeeper off, SAME MESSAGE.

**Comment by froxcey** [comment]
Hey I'm digging through the problem. When I test it locally, everything works. When I run it after downloading it, it breaks. You can watch a tutorial on how to make a Mac version yourself 
https://youtu.be/-7cY5KT8rdw

**Comment by erich666** [comment]
Ah, great, thanks for the tutorial - I've stored that link away now. Best of luck with the problem. I strongly suspect it's a Mac protection "feature", where they set some bit or field, but I haven't tried any of the things recommended to unquarantine (or whatever it is) the file.

I ran across this, https://appletoolbox.com/app-is-damaged-cannot-be-opened-mac/, which looks promising, but haven't tried tweaking the privacy settings yet.

**Comment by froxcey** [comment]
I found out the problem. It's something to do with Mac security. This requires you to run the command:
`xattr -cr path/to/Mineways-Mac-9.00.app`

**Comment by erich666** [comment]
Good find! I don't foresee users wanting to mess with commands, however, so maybe we need to not provide a Mac version. There are a few ways that people can run Mineways on a Mac themselves - some cost money, some need skills (such as WINE). I'd love a free, no technical knowledge needed version, but that's looking unlikely at best at this point.

**Comment by froxcey** [comment]
> I'd love a free, no technical knowledge needed version

@erich666 I send you a "free, no technical knowledge needed version" through email, a pkg file that prevents some weird download process from writing into the metadata of the app and allow users to install the app correctly.

**Comment by erich666** [comment]
I tried that and it didn't work for me - see my email reply. It's probably best to stop answering on this Github thread and stick to email. That will be less confusing for us both (i.e., knowing whether the Github comment here or email is the latest reply).

**Comment by erich666** [comment]
Solved! New 9.00 for the Mac is up and ready for download. Read the install instructions carefully: http://www.realtimerendering.com/erich/minecraft/public/mineways/downloads.html#mac
