### ISSUE TITLE
Render error

### ISSUE THREAD

**Issue by Maker261** [erich666/Mineways#91]
![Screenshot_2](https://user-images.githubusercontent.com/46901949/148062240-59708195-7ffd-45e5-aa8e-0f89c2946e3f.png)
Like it says in the screenshot, the chunks cannot be loaded cause of the "mods" that the world is using.
And here are the mods that I use
![Screenshot_3](https://user-images.githubusercontent.com/46901949/148062399-48ac9db6-dbd1-4fb4-aad0-bc76f0248a76.png)
None of these mods modify the world generation, its cause 1.18 has entirely changed the way the world generates, also including the negative height, and this world was created in 1.17 and later moved it to 1.18
Sooo yeah :/

EDIT: Yes, I am using mineways 9.08

**Comment by erich666** [comment]
Thanks for writing. First thing to try: the beta at http://www.realtimerendering.com/erich/minecraft/public/mineways/downloads/Mineways_V909beta1.zip

That may just fix things for you, end of story. If not, please do pack up your world into a zip file and put it somewhere I can download it. I'll let you know when I've grabbed it. You can email me the details; I'm at erich@acm.org

**Comment by Maker261** [comment]
the link doesn't work

**Comment by erich666** [comment]
It does work, but oddly, it doesn't work in Github itself (you can't just click the link in this message). If you paste http://www.realtimerendering.com/erich/minecraft/public/mineways/downloads/Mineways_V909beta1.zip into a browser, you'll download it. Or, try http://www.realtimerendering.com/erich/minecraft/public/mineways/downloads and then click on the Mineways beta there.

**Comment by Maker261** [comment]
ok got it, lets see if it works now

**Comment by erich666** [comment]
Oh, good - thanks for getting back to me. I'll close this one, knowing that I should be making a new release soon.
