### ISSUE TITLE
Error by importing .obj

### ISSUE THREAD

**Issue by GigaGamingYT** [erich666/Mineways#98]
Hey guys! an error occurred whilst importing an .obj-file into blender. can anyone help me?
![Bildschirmfoto vom 2022-07-07 16-08-29](https://user-images.githubusercontent.com/107420654/177793895-ffcb30c6-9f09-4a7c-8dd6-def46167c74c.png)

**Comment by GigaGamingYT** [comment]
i forgot to say, i use blender 2.93.3

**Comment by erich666** [comment]
Sorry to just notice this now (Github, why are you not sending me emails?). This is possibly a Mineways issue, so I'm of course interested. But without the OBJ (and MTL and PNGs), I can't tell much. Could you attach the files here, or email to me at erich@acm.org, or put them somewhere I can download them?

https://www.blender.org/community/ may be the next stop, if I can't figure it out.

**Comment by erich666** [comment]
Ping - could you send the OBJ, MTL, and PNG files to me so that I can follow up on this one?

**Comment by erich666** [comment]
One more ping, then I'll close this if no response. Please send on the OBJ/MTL/texture files. Also, try the latest version of Mineways - "individual texture" export is now the norm, which may work better for you.

**Comment by erich666** [comment]
No response, and trying Blender 3.5 recently, the (new) OBJ importer works much better than the old. I'll assume this one is not reproducible at this point. Closing.
