### ISSUE TITLE
General Improvements

### ISSUE THREAD

**Issue by StandingPadAnimations** [erich666/Mineways#99]
Mineways has a few issues I've noticed over time from helping people on the MCprep server. Here's some of the most common issues:
* Texture swap or animate textures not working out of the box (requires an extra option during exporting)
* Too many vertices and edges 

Normally I would suggest people to use jmc2OBJ, but jmc2OBJ requires Java to be installed (which then requires users to make sure they're using the 64 bit version of Java), which at times is hard to explain to people. Mineways meanwhile works out of the box, and in my experience exports faster (likely because it's coded in C++) As such, it would be nice for Mineways to have these issues resolved. Some of the suggestions I have include:
* Improved UI. I don't mean in a big way, but something as simple as a ? which when hovered over explains what the feature does. A small change like that goes a long way 
* Different defaults for textures. I think by defaults textures shouldn't use a single image, it causes more issues. 
* OBJ optimization. Right now Mineways OBJs are limited in size due to the amount of vertices and edges they contain. OBJ optimization would make OBJs easier to import for software like Blender, which means larger OBJs can be exported without resorting to hackish methods 

Overall I think if Mineways can improve in those areas, it would have a serious edge over other exporters, and would make user experience a whole lot better

**Comment by erich666** [comment]
I need to figure out why Github is not sending me alerts of new issues filed. I just noticed this one today. Sorry about that, and in the future I'll need to make it a weekly check of issues (which I do for Discord and Reddit).

> something as simple as a ? which when hovered over explains what the feature does

Nice idea. Unfortunately, I'm a beginner UI programmer when it comes to Microsoft's Windows system, so I don't know how to do this. Do you know of any open source (and Windows-based) UI that does this? (I don't, unfortunately.) I could copy their code and learn from it. I'm not trying to ignore this suggestion, just the opposite. But, I'm stuck with my own ignorance and not seeing this in any other Windows app I can think of. In the meantime, hopefully people notice the "Help" items in the menu, I guess. Maybe I should add a "what does the app mean overall?" page - that could be good!

> I think by defaults textures shouldn't use a single image, it causes more issues.

I've debated this with myself _so much_. I've stuck with the single texture for now, as it doesn't then spew a zillion little textures, just a few larger ones. I should put a poll on Discord and Reddit, etc.

>  OBJ optimization would make OBJs easier to import for software like Blender

Another thing I've thought a lot about and have passed on, so far. However, it's complicated, and probably should _not_ be done for grassy areas, for example. See https://github.com/erich666/Mineways/issues/60 for the technical discussion.

Anyway, thanks for the input, truly. I'll start asking on the various forums about texture defaults for OBJ (USD does use separate textures; really, I see it as the future. Which reminds me, I should see how Blender is doing supporting USD.

**Comment by erich666** [comment]
As far as not using a single image for the default export method, you can now vote & discuss on [Reddit](https://www.reddit.com/r/mineways/comments/zpzp3e/poll_change_default_obj_export_from_3_textures_to/) or [Discord](https://discord.com/channels/839554592669040680/844619553262534737/1054463995056242728).

**Comment by erich666** [comment]
Oh, and whatever gets decided, I'll leave the single texture export option the norm for 3D printing export, which is where it makes more sense (and can be the preferred method).

**Comment by erich666** [comment]
I finally figured out how to add tooltips to (most) dialog elements, so that's now done for the exports dialog: https://github.com/erich666/Mineways/releases/tag/v10.07

I couldn't figure out in WinAPI how to add tooltips to menu items. I googled for a fair while, found a bunch of things, but so far they either don't apply, don't work, or are poorly explained.

**Comment by erich666** [comment]
Mineways 10.10 now has mesh simplification. Thanks for asking for it - you helped motivate it happening. I did just find a bug today, that flat water and lava surfaces don't simplify, but that'll be fixed in 10.11. Otherwise it works surprisingly well, often actually reducing the overall time spent exporting the same model.

I think I've now addressed all the issues that Mineways can handle (I don't think there's much I can do for animated textures - let me know specifics, if there is).

**Comment by erich666** [comment]
Also, for animated texture support, there's a specific issue for that: https://github.com/erich666/Mineways/issues/9 - please add any ideas there. I'm happy to add special tags or comments for animatable textures in my OBJ and USD export files. I don't know what to do to support them otherwise.

**Comment by StandingPadAnimations** [comment]
> Also, for animated texture support, there's a specific issue for that

Animate texture support was related to textures not being exported as individual images by default, which was already changed. Sorry if I wasn't clear on that earlier
